package ge.luka.melodia.presentation.ui.theme.colors

import androidx.compose.material3.darkColorScheme

object ColorSchemes {

    val darkGreenScheme = darkColorScheme(
        primary = GreenColors.primaryDark,
        onPrimary = GreenColors.onPrimaryDark,
        primaryContainer = GreenColors.primaryContainerDark,
        onPrimaryContainer = GreenColors.onPrimaryContainerDark,
        secondary = GreenColors.secondaryDark,
        onSecondary = GreenColors.onSecondaryDark,
        secondaryContainer = GreenColors.secondaryContainerDark,
        onSecondaryContainer = GreenColors.onSecondaryContainerDark,
        tertiary = GreenColors.tertiaryDark,
        onTertiary = GreenColors.onTertiaryDark,
        tertiaryContainer = GreenColors.tertiaryContainerDark,
        onTertiaryContainer = GreenColors.onTertiaryContainerDark,
        error = GreenColors.errorDark,
        onError = GreenColors.onErrorDark,
        errorContainer = GreenColors.errorContainerDark,
        onErrorContainer = GreenColors.onErrorContainerDark,
        background = GreenColors.backgroundDark,
        onBackground = GreenColors.onBackgroundDark,
        surface = GreenColors.surfaceDark,
        onSurface = GreenColors.onSurfaceDark,
        surfaceVariant = GreenColors.surfaceVariantDark,
        onSurfaceVariant = GreenColors.onSurfaceVariantDark,
        outline = GreenColors.outlineDark,
        outlineVariant = GreenColors.outlineVariantDark,
        scrim = GreenColors.scrimDark,
        inverseSurface = GreenColors.inverseSurfaceDark,
        inverseOnSurface = GreenColors.inverseOnSurfaceDark,
        inversePrimary = GreenColors.inversePrimaryDark,
        surfaceDim = GreenColors.surfaceDimDark,
        surfaceBright = GreenColors.surfaceBrightDark,
        surfaceContainerLowest = GreenColors.surfaceContainerLowestDark,
        surfaceContainerLow = GreenColors.surfaceContainerLowDark,
        surfaceContainer = GreenColors.surfaceContainerDark,
        surfaceContainerHigh = GreenColors.surfaceContainerHighDark,
        surfaceContainerHighest = GreenColors.surfaceContainerHighestDark,
    )

    val darkBlueScheme = darkColorScheme(
        primary = BlueColors.primaryDark,
        onPrimary = BlueColors.onPrimaryDark,
        primaryContainer = BlueColors.primaryContainerDark,
        onPrimaryContainer = BlueColors.onPrimaryContainerDark,
        secondary = BlueColors.secondaryDark,
        onSecondary = BlueColors.onSecondaryDark,
        secondaryContainer = BlueColors.secondaryContainerDark,
        onSecondaryContainer = BlueColors.onSecondaryContainerDark,
        tertiary = BlueColors.tertiaryDark,
        onTertiary = BlueColors.onTertiaryDark,
        tertiaryContainer = BlueColors.tertiaryContainerDark,
        onTertiaryContainer = BlueColors.onTertiaryContainerDark,
        error = BlueColors.errorDark,
        onError = BlueColors.onErrorDark,
        errorContainer = BlueColors.errorContainerDark,
        onErrorContainer = BlueColors.onErrorContainerDark,
        background = BlueColors.backgroundDark,
        onBackground = BlueColors.onBackgroundDark,
        surface = BlueColors.surfaceDark,
        onSurface = BlueColors.onSurfaceDark,
        surfaceVariant = BlueColors.surfaceVariantDark,
        onSurfaceVariant = BlueColors.onSurfaceVariantDark,
        outline = BlueColors.outlineDark,
        outlineVariant = BlueColors.outlineVariantDark,
        scrim = BlueColors.scrimDark,
        inverseSurface = BlueColors.inverseSurfaceDark,
        inverseOnSurface = BlueColors.inverseOnSurfaceDark,
        inversePrimary = BlueColors.inversePrimaryDark,
        surfaceDim = BlueColors.surfaceDimDark,
        surfaceBright = BlueColors.surfaceBrightDark,
        surfaceContainerLowest = BlueColors.surfaceContainerLowestDark,
        surfaceContainerLow = BlueColors.surfaceContainerLowDark,
        surfaceContainer = BlueColors.surfaceContainerDark,
        surfaceContainerHigh = BlueColors.surfaceContainerHighDark,
        surfaceContainerHighest = BlueColors.surfaceContainerHighestDark,
    )
}