package ge.luka.melodia.presentation.ui.theme.colors

import androidx.compose.ui.graphics.Color
object GreenColors {
    val primaryDark = Color(0xFF94D5A8)
    val onPrimaryDark = Color(0xFF00391E)
    val primaryContainerDark = Color(0xFF0E5130)
    val onPrimaryContainerDark = Color(0xFFB0F1C3)
    val secondaryDark = Color(0xFFB6CCB9)
    val onSecondaryDark = Color(0xFF213527)
    val secondaryContainerDark = Color(0xFF374B3D)
    val onSecondaryContainerDark = Color(0xFFD1E8D5)
    val tertiaryDark = Color(0xFFA3CDDB)
    val onTertiaryDark = Color(0xFF023640)
    val tertiaryContainerDark = Color(0xFF214C57)
    val onTertiaryContainerDark = Color(0xFFBEEAF7)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0F1511)
    val onBackgroundDark = Color(0xFFDFE4DD)
    val surfaceDark = Color(0xFF0F1511)
    val onSurfaceDark = Color(0xFFDFE4DD)
    val surfaceVariantDark = Color(0xFF414942)
    val onSurfaceVariantDark = Color(0xFFC0C9C0)
    val outlineDark = Color(0xFF8A938B)
    val outlineVariantDark = Color(0xFF414942)
    val scrimDark = Color(0xAA000000)
    val inverseSurfaceDark = Color(0xFFDFE4DD)
    val inverseOnSurfaceDark = Color(0xFF2C322D)
    val inversePrimaryDark = Color(0xFF2C6A46)
    val surfaceDimDark = Color(0xFF0F1511)
    val surfaceBrightDark = Color(0xFF353B36)
    val surfaceContainerLowestDark = Color(0xFF0A0F0C)
    val surfaceContainerLowDark = Color(0xFF181D19)
    val surfaceContainerDark = Color(0xFF1C211D)
    val surfaceContainerHighDark = Color(0xFF262B27)
    val surfaceContainerHighestDark = Color(0xFF313631)
}